function Path_info_list = fn_direct_path_info(is_contact, probe_coords, model_options)

mode_names = ["L", "T"];
speeds = [model_options.material.v_L, model_options.material.v_S];

num_paths = 2;

Path_info_list = repmat(fn_path_info( ...
        "", ...
        "", ...
        [0], ...
        0, ...
        0, ...
        [model_options.material.couplant_v, model_options.material.v_L, model_options.material.v_S], ...
        [1], ...
        [model_options.material.couplant_density, model_options.material.density], ...
        0, ...
        0, ...
        0, ...
        probe_coords, ...
        model_options.mesh.n_per_wl ...
    ), ...
    num_paths, 1 ...
);

path = 1;
%% Contact
if is_contact
    path_geometry = 0;
    for mode = 0:1
        mode_name = mode_names(mode+1);
        Direct_path_info = fn_path_info( ...
            mode_name, ...
            mode_name, ...
            [mode], ...
            path_geometry, ...
            speeds(mode+1), ...
            [model_options.material.couplant_v, model_options.material.v_L, model_options.material.v_S], ...
            [1], ... % index for material identity
            [model_options.material.couplant_density, model_options.material.density], ...
            model_options.probe.freq, ...
            model_options.probe.width + model_options.probe.separation, ...
            model_options.probe.width, ...
            probe_coords, ...
            model_options.mesh.n_per_wl ...
        );
        Path_info_list(path) = Direct_path_info;
        path = path + 1;
        clear Direct_path_info
    end

    clear path_geometry

%% Immersion
elseif ~is_contact
    % Find the front wall
    geometry = model_options.mesh.geom.geometry;
    wall_names = repmat("", size(geometry, 1), 1);
    for wall = 1:size(geometry, 1)
        wall_names(wall) = geometry(wall).name;
    end
    where_F = logical(count(wall_names, "F"));
    path_geometry = geometry(where_F);

    for mode = 0:1
        mode_name = mode_names(mode+1);
        Direct_path_info = fn_path_info( ...
            mode_name, ...
            mode_name, ...
            [0, mode], ...
            path_geometry, ...
            [model_options.material.couplant_v, speeds(mode+1)], ...
            [model_options.material.couplant_v, model_options.material.v_L, model_options.material.v_S], ...
            [0, 1], ...
            [model_options.material.couplant_density, model_options.material.density], ...
            model_options.probe.freq, ...
            model_options.probe.width + model_options.probe.separation, ...
            model_options.probe.width, ...
            probe_coords, ...
            model_options.mesh.n_per_wl ...
        );
        Path_info_list(path) = Direct_path_info;
        path = path + 1;
        clear Direct_path_info
    end
end

end